config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', lambda request : redirect('jobs/')),
    path('jobs/', include('jobs.urls')),
    path('news/', include('news.urls')),
    path('reviews/', include('reviews.urls')),
    path('interviews/', include('interviews.urls')),
    path('common/', include('common.urls')),

]

jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'
#
urlpatterns = [
    path('',  views.index, name='index'),
]

reviews/urls.py
from django.urls import path

from . import views

app_name = 'reviews'

urlpatterns = [
    path('',  views.review_list, name='review_list'),
    path('detail/<int:rev_com_id>/',  views.review_detail, name='review_detail'),
]

reviews/models.py
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class Company(models.Model):
    com_id = models.CharField(primary_key=True, max_length=50)
    com_name = models.CharField(max_length=50)
    com_location = models.CharField(max_length=800, blank=True, null=True)
    com_employees = models.CharField(max_length=300, blank=True, null=True)
    com_size = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'company'


class Cv(models.Model):
    cv_id = models.CharField(primary_key=True, max_length=50)
    cv_company = models.CharField(max_length=50, blank=True, null=True)
    cv_spec = models.CharField(max_length=1000, blank=True, null=True)
    cv_question = models.CharField(max_length=5000, blank=True, null=True)
    cv_answer = models.CharField(max_length=5000, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'cv'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Interview(models.Model):
    int_id = models.CharField(primary_key=True, max_length=50)
    int_com_id = models.CharField(max_length=50)
    name_list = models.CharField(max_length=50)
    int_difficulty = models.CharField(max_length=50, blank=True, null=True)
    int_date = models.CharField(max_length=50, blank=True, null=True)
    int_question = models.CharField(max_length=5000, blank=True, null=True)
    int_answer = models.CharField(max_length=5000, blank=True, null=True)
    int_result = models.CharField(max_length=50, blank=True, null=True)
    int_post_date = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'interview'


class News(models.Model):
    news_id = models.CharField(primary_key=True, max_length=50)
    news_com_id = models.CharField(max_length=50, blank=True, null=True)
    news_title = models.CharField(max_length=500)
    news_href = models.CharField(max_length=500, blank=True, null=True)
    news_date = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'news'


class Post(models.Model):
    post_id = models.CharField(primary_key=True, max_length=50)
    post_com_id = models.CharField(max_length=50)
    post_com_name = models.CharField(max_length=500, blank=True, null=True)
    post_title = models.CharField(max_length=500)
    post_career = models.CharField(max_length=500)
    post_location = models.CharField(max_length=800, blank=True, null=True)
    post_emp_types = models.CharField(max_length=500, blank=True, null=True)
    post_dday = models.CharField(max_length=50, blank=True, null=True)
    post_pay = models.CharField(max_length=100, blank=True, null=True)
    post_href = models.CharField(max_length=500)

    class Meta:
        managed = False
        db_table = 'post'


class Review(models.Model):
    rev_id = models.CharField(primary_key=True, max_length=50)
    rev_com_id = models.CharField(max_length=50)
    rev_com_name = models.CharField(max_length=500)
    rev_rate = models.CharField(max_length=50, blank=True, null=True)
    rev_title = models.CharField(max_length=1000)
    rev_date = models.CharField(max_length=50, blank=True, null=True)
    rev_part = models.CharField(max_length=200, blank=True, null=True)
    rev_now = models.CharField(max_length=200, blank=True, null=True)
    rev_strength = models.CharField(max_length=5000, blank=True, null=True)
    rev_weakness = models.CharField(max_length=5000, blank=True, null=True)
    rev_wish = models.CharField(max_length=5000, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'review'


class Users(models.Model):
    user_id = models.CharField(primary_key=True, max_length=50)
    pwd = models.CharField(max_length=100)
    email = models.CharField(max_length=200)
    phone = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'users'

reviews/views.py
from django.shortcuts import render
from .models import Review
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q

def review_list(request):

    review_list = Review.objects.all().order_by('-rev_com_name')
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')  # 검색어

    if kw:
        review_list = review_list.filter(
            Q(rev_title__icontains=kw) |  # 제목 검색
            Q(rev_com_name__icontains=kw)  # 회사명 검색
        ).distinct()

    paginator = Paginator(review_list, 10)
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page = 1
        page_obj = paginator.page(page)
    except EmptyPage:
        page = paginator.num_pages
        page_obj = paginator.page(page)

    leftIndex = (int(page) - 2)
    rightIndex = (int(page) + 2)

    if leftIndex < 1:
        leftIndex = 1

    if rightIndex > paginator.num_pages:
        rightIndex = paginator.num_pages

    custom_range = range(leftIndex, rightIndex + 1)

    return render(request, 'reviews/review.html', {
                                                'review_list': review_list,
                                                'page_obj': page_obj,
                                                'paginator': paginator,
                                                'custom_range': custom_range,
                                                'page': page,
                                                'kw': kw})



def review_detail(request, rev_com_id):
    review_com_list = Review.objects.filter(rev_com_id=rev_com_id)
    review_1 = review_com_list[0]
    return render(request, 'reviews/review_detail.html', {'review': review_com_list, 'review_1': review_1})

templates/reviews/review.html
{% extends 'base.html' %}
{% load list_filter %}
{% block content %}

<!-- Header-->
<header class="bg-primary bg-gradient text-white" style="margin-bottom:100px;">

</header>


<!-- search section-->
    <section id="about">
           <div class="container">
                <div class="row my-3" style="position: relative;">
                    <div class="col-6" style="align:right;">
                        <div class="input-group" style="max-width: 350px;">
                            <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                            <div class="input-group-append" style="margin-left:10px;">
                                <button class="btn btn-outline-secondary" type="button" id="btn_search">검색</button>
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </section>

<!-- list section-->
<section class="bg-light" id="review_list">
    <div class="container px-4">
        <div class="row justify-content-center">
<!--            <div class="col-lg-10">-->
                  <table class="rwd-table" style="table-layout:fixed;">
                    <tbody>
                    {% if review_list %}
                      <tr>
                        <th style="width:50px;text-align:center;">번호</th>
                        <th style="text-overflow:ellipsis;width:600px;text-align:center;">제목</th>
                        <th style="text-align:center;">회사명</th>
                        <th style="text-align:center;">부서</th>
                        <th style="text-overflow:ellipsis;width:130px;text-align:center;">평점</th>
                        <th style="text-align:center;">작성일</th>
                      </tr>
                     {% for r in page_obj %}
                      <tr>
                        <td style="text-align:center;" nowrap>  {{page_obj.start_index|add:forloop.counter0}} </td>
                        <td style="text-align:left;" nowrap> <a href="{% url 'reviews:review_detail' r.rev_com_id %}">{{ r.rev_title }}</a></td>
                        <td style="text-align:center;" nowrap> {{ r.rev_com_name }}</td>
                        <td style="text-align:center;" > {{ r.rev_part }} </td>
                        <td style="text-align:center;" > {{ r.rev_rate }} </td>
                        <td style="text-align:center;"> {{ r.rev_date }} </td>
                      </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                        <th style="width:50px;text-align:center;">번호</th>
                        <th style="text-overflow:ellipsis;width:400px;text-align:center;">제목</th>
                        <th style="text-align:center;">회사명</th>
                        <th style="text-align:center;">부서</th>
                        <th style="text-overflow:ellipsis;max-width:100px;text-align:center;">평점</th>
                        <th style="text-align:center;">작성일</th>
                      </tr>
                    <tr>
                        <td colspan="6" style="text-align:center"><h3>자료가 없어용</h3></td>
                    </tr>
                    {% endif %}
                    </tbody>
                  </table>

                   <!-- 페이징처리 시작 -->
                  <ul class="pagination justify-content-center">
                        <!-- 이전페이지 -->
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" data-page="{{ page_obj.previous_page_number }}"
                            href="javascript:void(0)">이전</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
                        </li>
                        {% endif %}
                        <!-- 페이지리스트 -->
                        {% for page_number in custom_range %}
                        {% if page_number == page_obj.number %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" data-page="{{ page_number }}"
                               href="javascript:void(0)">{{ page_number }}</a>
                        </li>
                        {% else %}
                        <li class="page-item">
                            <a class="page-link" data-page="{{ page_number }}"
                              href="javascript:void(0)">{{ page_number }}</a>
                        </li>
                        {% endif %}
                        {% endfor %}
                        <!-- 다음페이지 -->
                        {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" data-page="{{ page_obj.next_page_number }}"
                               href="javascript:void(0)">다음</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
                        </li>
                        {% endif %}
                  </ul>
                    <!-- 페이징처리 끝 -->
        </div>
    </div>
</section>

<form id="searchForm" method="get" action="{% url 'reviews:review_list' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}

templates/reviews/review_detail.html
{% extends 'base.html' %}
{% load list_filter %}
{% block content %}

<!-- Header-->
<header class="bg-primary bg-gradient text-white" style="margin-bottom:100px;">

</header>

<div class="container my-3">

    <!-- 회사이름 -->
    <h2 class="border-bottom py-2">{{ review_1.rev_com_name }}</h2>

    {% if review %}
    <!-- 후기 목록 -->
    <h5 class="border-bottom my-3 py-2">{{review.count}}개의 회사 후기가 있습니다.</h5>
    {% for r in review %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;"><h5 style="background:#000000;color:#ffffff">{{ r.rev_title }}</h5></div>
            <div class="card-text" style="white-space: pre-line;">
            <div class='lead'> 장점 </div> {{ r.rev_strength }}
            </div>
            <div class="card-text" style="white-space: pre-line;">
            <div class='lead'> 단점 </div> : {{ r.rev_weakness }}
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ r.rev_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <h5 class="border-bottom my-3 py-2">아직 후기가 없습니다.</h5>
    {% endif %}
</div>
{% endblock %}