common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', lambda request : redirect('jobs/')),
    path('jobs/', include('jobs.urls')),
    path('news/', include('news.urls')),
    path('reviews/', include('reviews.urls')),
    path('interviews/', include('interviews.urls')),
    path('common/', include('common.urls')),

]

interviews/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'interviews'

urlpatterns = [
    path('', views.interview_list, name='interview_list'),
    path('detail/<str:name_list>/',  views.interview_detail, name='interview_detail'),
]

jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'
#
urlpatterns = [
    path('',  views.index, name='index'),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('',  views.news_list, name='news_list'),
]

reviews/urls.py
from django.urls import path

from . import views

app_name = 'reviews'

urlpatterns = [
    path('',  views.review_list, name='review_list'),
    path('detail/<int:rev_com_id>/',  views.review_detail, name='review_detail'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
        <!-- pybo CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'table.css' %}">
        <script src="https://kit.fontawesome.com/41331008ef.js" crossorigin="anonymous"></script>
        <title>취뽀</title>
    </head>
    <body id="page-top">
    <!-- 네비게이션바 -->
    {% include "navbar.html" %}
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}



    {% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container px-4"><p class="m-0 text-center text-white">Copyright &copy; 꼬끼오즈 WEB 2023</p></div>
</footer>

<!-- Core theme JS-->
<script src="{% static 'scripts.js' %}"></script>
<!-- Bootstrap core JS-->
<script src="{% static 'bootstrap.min.js' %}"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>



{% block script %}
<script type='text/javascript'>


const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();

});
</script>
{% endblock %}
</body>
</html>

templates/form_errors.html
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!--  필드 오류: 사용자 입력값에 대한 오류  -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<!-- Navigation-->
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
            <div class="container px-4">
                <a class="navbar-brand" href="{% url 'jobs:index' %}">취뽀 PROJECT</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto" style="text-align:center; margin-left:auto; margin-right:33%;">
                        <li class="nav-item"><a class="nav-link" href="{% url 'jobs:index' %}">채용</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'interviews:interview_list' %}">면접</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'reviews:review_list' %}">리뷰</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'news:news_list' %}">뉴스</a></li>
                    </ul>
                    <div>
                         <div>
                             {% if user.is_authenticated %}
                            <a href="#" style="margin-right:10px">{{ user.username }} </a>
                            <a class="btn btn-primary" href="{% url 'common:logout' %}" style="background:white;color:#000000; border-color:white;height:30px;padding-bottom:25px;">로그아웃</a>
                            {% else %}
                            <a class="btn btn-primary" href="{% url 'common:login' %}" style="background:white;color:#000000; border-color:white;height:30px;padding-bottom:25px;">로그인</a>
                            {% endif %}
                            <a class="btn btn-primary" href="{% url 'common:signup' %}" style="background:white;color:#000000; border-color:white;height:30px;padding-bottom:25px;">회원가입</a>
                        </div>
                    </div>
                </div>
            </div>
        </nav>